server:
  port: 9001
spring:
  application:
    name: PINGGOU-PRODUCT
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///pinggou-product?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root
mybatis-plus:
  type-aliases-package: cn.itsource.pinggou.domain,cn.itsource.pinggou.query
  
feign:
   hystrix:
     #开启熔断支持
     enabled: true 
   client:
     config:
       remote-service:   #服务名，填写default为所有服务
         connectTimeout: 5000
         readTimeout: 5000
