server:
  port: 9529
spring:
  application:
    name: PINGGOU-ZUUL-GATEWAY
zuul:
  routes:
    plat:
      serviceId: pinggou-plat #这是调用满足条件的服务名，注意要小写
      path: /plat/** #这是所有路径前的通配
    product:
      serviceId: pinggou-product #这是调用满足条件的服务名，注意要小写
      path: /product/** #这是所有路径前的通配
  ignored-services: "*" #用*来通配符，忽略从9527端口通过服务名来调用
  prefix: "/services" #这是所有路径的前缀
hystrix:
  command:
    myusers-service:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000
pinggou-product: 
  ribbon:
    ConnectTimeout: 1000
    ReadTimeout: 5000
